<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="NuevoPedido.aspx.cs" Inherits="CompraComponentes.Formularios.NuevoPedido" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                url: "../Controladores/ControladorTodosProveedores.ashx",
                success: function (proveedoresJSON) {
                    proveedores = jQuery.parseJSON(proveedoresJSON);
                    proveedores.forEach(proveedor => {
                        $('#cboProveedores').append('<option value= ' + proveedor.CodProveedor + '>' + proveedor.NombreProveedor + '</option>');
                    });
                },
                errores: function () { }
            });

            $.ajax({
                url: "../Controladores/ControladorTodosProductos.ashx",
                success: function (productosJSON) {
                    productos = jQuery.parseJSON(productosJSON);
                    productos.forEach(producto => {
                        $('#cboProductos').append('<option value= ' + producto.CodProducto + '>' + producto.NombreProd + '</option>');
                    });
                },
                errores: function () { }
            });

            $("#btnalta").click(function () {
                codPedido = $('#txtNCodPedido').val();
                codProveedor = $('#cboProveedores').val();
                codProducto = $('#cboProductos').val();
                unidades = $('#txtNUnidades').val();
                $.ajax({
                    url: '../Controladores/ControladorAñadirPedido.ashx',
                    type: 'get',
                    async: true,
                    data: { CodPedido: codPedido, CodProveedor: codProveedor, CodProducto: codProducto, Unidades: unidades },
                    success: function (res) {
                        if (res == 0) {
                            $('#divRes').text('Linea de pedido añadida');
                        }
                        else if (res == 1) {
                            $('#divRes').text('Pedido añadido');
                        }
                    }
                });
            });
        });
    </script>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <div id="divRes"></div>
            CodPedido: <input id="txtNCodPedido" type="text" /><br />
            CodProveedor: <select name="cboProveedores" id="cboProveedores">
					        <option value="-1" selected="selected">-- PROVEEDORES --</option>
                       </select><br />
            CodProducto: <select name="cboProductos" id="cboProductos">
					        <option value="-1" selected="selected">-- PRODUCTOS --</option>
                       </select><br />
            Unidades: <input id="txtNUnidades" type="text" /><br />
            <asp:Button ID="btnalta" runat="server" Text="Añadir Pedido" /><br />

            <asp:LinkButton ID="btnlVerProveedores" runat="server" OnClick="btnlVerProveedores_Click">Ver Proveedores</asp:LinkButton>
            <asp:LinkButton ID="btnlVerProductos" runat="server" OnClick="btnlVerProductos_Click">Ver Productos</asp:LinkButton><br />

            <br /><asp:Label ID="Label1" runat="server" Text="Inserte código de pedido para buscar"></asp:Label>
            <br /><asp:TextBox ID="txtCodPedido" runat="server"></asp:TextBox>
            <asp:Button ID="btnBuscar" runat="server" Text="Buscar" />

            <asp:ObjectDataSource ID="or_Pedidos" runat="server" SelectMethod="MostrarPedidos" TypeName="CompraComponentes.App_Code.DB_Pedidos" DeleteMethod="EliminarPedido">
                <DeleteParameters>
                    <asp:Parameter Name="CodPedido" Type="Int32"></asp:Parameter>
                </DeleteParameters>
                <SelectParameters>
                    <asp:ControlParameter ControlID="txtCodPedido" PropertyName="Text" Name="CodPedido" Type="Int32"></asp:ControlParameter>
                </SelectParameters>
            </asp:ObjectDataSource>
            <br /><asp:Label ID="Label2" runat="server" Text="PEDIDOS"></asp:Label>
            <asp:GridView ID="grd_Pedidos" runat="server"
                AutoGenerateColumns="False"
                DataSourceID="or_Pedidos"
                DataKeyNames="CodPedido" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True">
                <Columns>
                    <asp:BoundField DataField="CodPedido" HeaderText="CodPedido" SortExpression="CodPedido"></asp:BoundField>
                    <asp:BoundField DataField="FechaPedido" HeaderText="FechaPedido" SortExpression="FechaPedido"></asp:BoundField>
                    <asp:BoundField DataField="FechaEntrega" HeaderText="FechaEntrega" SortExpression="FechaEntrega"></asp:BoundField>
                </Columns>
            </asp:GridView><br />

            <asp:ObjectDataSource ID="or_CrudPedidos" runat="server"
                DeleteMethod="EliminarLineaPedido"
                SelectMethod="MostrarPedidosCodPedido"
                TypeName="CompraComponentes.App_Code.DB_Pedidos"
                UpdateMethod="ActualizarLineaPedido">
                <DeleteParameters>
                    <asp:Parameter Name="NumLinea" Type="Int32"></asp:Parameter>
                </DeleteParameters>
                <SelectParameters>
                    <asp:ControlParameter ControlID="grd_Pedidos"
                        PropertyName="SelectedValue"
                        Name="CodPedido"
                        Type="Int32"></asp:ControlParameter>
                </SelectParameters>
                <UpdateParameters>
                    <asp:Parameter Name="CodPedido" Type="Int32"></asp:Parameter>
                    <asp:Parameter Name="NumLinea" Type="Int32"></asp:Parameter>
                    <asp:Parameter Name="CodProveedor" Type="Int32"></asp:Parameter>
                    <asp:Parameter Name="CodProducto" Type="Int32"></asp:Parameter>
                    <asp:Parameter Name="unidades" Type="Int32"></asp:Parameter>
                </UpdateParameters>
            </asp:ObjectDataSource>

            <asp:Label ID="Label3" runat="server" Text="BUSCAR PEDIDOS POR PROVEEDOR"></asp:Label>
            <asp:GridView ID="grd_LineasDePedidos" runat="server" 
                AutoGenerateColumns="False" 
                DataSourceID="or_CrudPedidos" 
                AutoGenerateDeleteButton="True" 
                AutoGenerateEditButton="True" 
                DataKeyNames="NumLinea" 
                AutoGenerateSelectButton="False">
                <Columns>
                    <asp:BoundField DataField="CodPedido" HeaderText="CodPedido" SortExpression="CodPedido"></asp:BoundField>
                    <asp:BoundField DataField="NumLinea" HeaderText="NumLinea" SortExpression="NumLinea"></asp:BoundField>
                    <asp:BoundField DataField="CodProveedor" HeaderText="CodProveedor" SortExpression="CodProveedor"></asp:BoundField>
                    <asp:BoundField DataField="CodProducto" HeaderText="CodProducto" SortExpression="CodProducto"></asp:BoundField>
                    <asp:BoundField DataField="Unidades" HeaderText="Unidades" SortExpression="Unidades"></asp:BoundField>
                </Columns>
            </asp:GridView>
        </div>
    </form>
</body>
</html>
